### ISSUE TITLE
Can't sync using Docker image

### ISSUE THREAD

**Issue by nazar-pc** [centrifuge/centrifuge-chain#514]
I have a similar issue to #320 trying to run an archival node with following docker-compose.yml:
```yml
version: '2'

services:
  altair:
    image: centrifugeio/centrifuge-chain:parachain-latest
    ports:
      - 19953:9944
    volumes:
      - ./altair:/data
    command: [
      "centrifuge-chain",
      "--base-path", "/data",
      "--chain", "altair",
      "--pruning", "archive",
      "--ws-external",
      "--rpc-external",
      "--rpc-cors", "all",
    ]
```

Relay chain sync works, parachain not:
```
altair_1  | 2021-10-23 00:14:20 [Parachain] 💤 Idle (0 peers), best: #0 (0xaa38…0011), finalized #0 (0xaa38…0011), ⬇ 0.2kiB/s ⬆ 0.2kiB/s    
altair_1  | 2021-10-23 00:14:20 [Relaychain] ⚙️  Syncing 306.0 bps, target=#7377430 (20 peers), best: #58236 (0x6f8a…422f), finalized #57856 (0x5380…0372), ⬇ 185.4kiB/s ⬆ 23.1kiB/s    
```
